(function(){
  let activeChat=null;
  const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const fmtTime=v=>{if(!v)return '';const d=new Date(v);return isNaN(d)?'':d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})};
  const chats=()=>{const contacts=data.contacts||[];return contacts.map(c=>{const msgs=(data.messages||[]).filter(m=>m.sender_id===c.id||m.receiver_id===c.id);const last=msgs[msgs.length-1];const unread=msgs.filter(m=>m.receiver_id===me.id&&!m.read_at).length;return {...c,last,unread}}).sort((a,b)=>String(b.last?.created_at||'').localeCompare(String(a.last?.created_at||'')))};
  function renderPeople(list){if(!list.length)return '<div class="chat-empty-list">Пока нет доступных контактов.</div>';return list.map(c=>`<button class="chat-person ${c.id===activeChat?'active':''}" onclick="openChat('${c.id}')"><span class="chat-avatar">${initials(c.name)}</span><span class="chat-person-info"><span class="chat-person-top"><span class="chat-person-name">${esc(c.name)}</span><span class="chat-time">${fmtTime(c.last?.created_at)}</span></span><span class="chat-preview">${c.last?esc(c.last.text):'Начните новый разговор'}</span></span>${c.unread?`<span class="chat-unread">${c.unread}</span>`:''}</button>`).join('')}
  function renderChat(c){const msgs=(data.messages||[]).filter(m=>m.sender_id===c.id||m.receiver_id===c.id).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const body=msgs.length?msgs.map(m=>`<div class="chat-row ${m.sender_id===me.id?'mine':''}"><div class="chat-bubble"><div class="chat-text">${esc(m.text)}</div><div class="chat-meta">${fmtTime(m.created_at)} ${m.sender_id===me.id?(m.read_at?'✓✓':'✓'):''}</div></div></div>`).join(''):'<div class="chat-start"><div><div class="chat-start-icon">👋</div><h3>Начните разговор</h3><p>Напишите первое сообщение.</p></div></div>';return `<header class="chat-head"><button class="chat-mobile-back" onclick="closeChat()">‹</button><span class="chat-head-avatar">${initials(c.name)}</span><span class="chat-head-info"><h3>${esc(c.name)}</h3><small>${roles[c.role]||''}</small></span></header><div class="chat-body" id="chatBody">${body}</div><div class="chat-composer"><textarea class="chat-input" id="chatInput" rows="1" placeholder="Напишите сообщение…" onkeydown="chatKey(event)"></textarea><button class="chat-send" id="chatSend" onclick="sendChatMessage()">Отправить</button></div>`}
  function messages(){const list=chats();if(activeChat&&!list.some(x=>x.id===activeChat))activeChat=null;const selected=list.find(x=>x.id===activeChat);return `<div class="chat-app ${selected?'chat-open':''}"><aside class="chat-list"><div class="chat-list-head"><h2>Сообщения</h2><input class="chat-search" id="chatSearch" placeholder="Поиск контакта…" oninput="filterChats(this.value)"></div><div class="chat-people" id="chatPeople">${renderPeople(list)}</div></aside><section class="chat-window">${selected?renderChat(selected):'<div class="chat-start"><div><div class="chat-start-icon">💬</div><h2>Ваши сообщения</h2><p>Выберите контакт слева, чтобы начать разговор.</p></div></div>'}</section></div>`}
  window.openChat=async function(id){activeChat=id;render();requestAnimationFrame(()=>{const b=document.getElementById('chatBody');if(b)b.scrollTop=b.scrollHeight});const unread=(data.messages||[]).filter(m=>m.sender_id===id&&m.receiver_id===me.id&&!m.read_at);for(const m of unread){try{await api('/api/messages/'+m.id+'/read')}catch(e){}}if(unread.length){await load();render()}};
  window.closeChat=function(){activeChat=null;render()};
  window.filterChats=function(q){const value=String(q||'').toLowerCase();const list=chats().filter(c=>String(c.name).toLowerCase().includes(value)||String(roles[c.role]||'').toLowerCase().includes(value));const el=document.getElementById('chatPeople');if(el)el.innerHTML=renderPeople(list)};
  window.chatKey=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChatMessage()}};
  window.sendChatMessage=async function(){const input=document.getElementById('chatInput');const text=input?.value.trim();if(!activeChat||!text)return;if(text.length>2000)return notify('Сообщение слишком длинное',true);const btn=document.getElementById('chatSend');if(btn)btn.disabled=true;try{await api('/api/messages',{method:'POST',body:JSON.stringify({receiver_id:activeChat,text})});await load();render();requestAnimationFrame(()=>{const b=document.getElementById('chatBody');if(b)b.scrollTop=b.scrollHeight})}catch(e){notify(e.message,true)}finally{if(btn)btn.disabled=false}};
  const oldRender=window.render;window.render=function(){oldRender();if(window.view==='messages')requestAnimationFrame(()=>{const b=document.getElementById('chatBody');if(b)b.scrollTop=b.scrollHeight})};
})();
