const KEY='journal_pro_v1';
const seed={users:[{id:'t1',role:'teacher',name:'Учитель Demo',email:'teacher@demo.local',password:'1234'},{id:'s1',role:'student',name:'Ученик Demo',email:'student@demo.local',password:'1234',teacherId:'t1'},{id:'p1',role:'parent',name:'Родитель Demo',email:'parent@demo.local',password:'1234',studentId:'s1'}],students:[{id:'s1',name:'Ученик Demo',className:'10-А'}],subjects:[{id:'math',name:'Математика'},{id:'eng',name:'Английский'}],grades:[{studentId:'s1',subjectId:'math',value:9},{studentId:'s1',subjectId:'eng',value:8}],notifications:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed,session=JSON.parse(localStorage.getItem(KEY+'_session')||'null');
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const toast=m=>{let x=document.querySelector('#toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)};
const avg=id=>{let a=db.grades.filter(g=>g.studentId===id);return a.length?(a.reduce((s,g)=>s+Number(g.value),0)/a.length).toFixed(2):'0.00'};
function login(){let e=email.value.trim(),p=password.value,u=db.users.find(x=>x.email===e&&x.password===p);if(!u)return toast('Неверный email или пароль');session=u;localStorage.setItem(KEY+'_session',JSON.stringify(u));render()};function logout(){session=null;localStorage.removeItem(KEY+'_session');render()}
function student(u){return db.students.find(s=>s.id===(u.role==='student'?u.id:u.studentId))||db.students[0]};function ai(s){let a=avg(s.id),g=db.grades.filter(x=>x.studentId===s.id),w=g.filter(x=>x.value<=5).length;return `Средний балл: ${a}. ${w?`Низких оценок: ${w}. Рекомендуется повторить соответствующие темы.`:'Успеваемость стабильная. Можно повышать сложность заданий.'}`}
function report(s){return `<div class="card"><h2>📄 Отчёт: ${esc(s.name)}</h2><p>Средний балл: <b>${avg(s.id)}</b></p><button onclick="window.print()">Печать / PDF</button></div>`}
function teacher(){return `<div class="grid"><div class="stat">Ученики<strong>${db.students.length}</strong></div><div class="stat">Предметы<strong>${db.subjects.length}</strong></div><div class="stat">Оценки<strong>${db.grades.length}</strong></div><div class="stat">Уведомления<strong>${db.notifications.length}</strong></div></div><div class="card"><h2>👨‍🎓 Ученики</h2><table class="table"><tr><th>Имя</th><th>Класс</th><th>Средний</th></tr>${db.students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.className)}</td><td>${avg(s.id)}</td></tr>`).join('')}</table></div><div class="card"><h2>🔔 Уведомления</h2><div class="row"><input id="notice" placeholder="Текст"><button onclick="addNotice()">Отправить</button></div></div>`}
function family(u){let s=student(u);return `<div class="grid"><div class="stat">Средний балл<strong>${avg(s.id)}</strong></div><div class="stat">Оценок<strong>${db.grades.filter(g=>g.studentId===s.id).length}</strong></div></div>${report(s)}<div class="card"><h2>🤖 AI-анализ</h2><p>${esc(ai(s))}</p></div>`}
function addNotice(){let t=document.querySelector('#notice').value.trim();if(!t)return;db.notifications.unshift({text:t,date:Date.now()});save();render();toast('Уведомление отправлено')}
function sync(){save();toast('☁️ Локальные данные сохранены. Backend нужен для реальной облачной синхронизации.')}
function render(){if(!session){app.innerHTML=`<div class="shell"><div class="login card"><h1>📘 School Journal Pro</h1><p>🔐 Авторизация</p><div class="form"><input id="email" placeholder="Email"><input id="password" type="password" placeholder="Пароль"><button onclick="login()">Войти</button></div><div class="notice">Demo: teacher@demo.local / 1234<br>student@demo.local / 1234<br>parent@demo.local / 1234</div></div></div>`;return}let body=session.role==='teacher'?teacher():family(session);app.innerHTML=`<div class="shell"><div class="top"><div class="brand">📘 School Journal Pro</div><div class="row"><span class="pill">${esc(session.role)}</span><button class="secondary" onclick="sync()">☁️ Синхронизация</button><button class="danger" onclick="logout()">Выйти</button></div></div><div id="content">${body}</div></div>`};render();
