import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import PDFDocument from 'pdfkit';
import webpush from 'web-push';

const app=express(); app.use(cors()); app.use(express.json({limit:'1mb'}));
const db=new Database(process.env.DB_FILE||'school.db');
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('teacher','student','parent')),student_id INTEGER);CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,class_name TEXT NOT NULL);CREATE TABLE IF NOT EXISTS subjects(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL);CREATE TABLE IF NOT EXISTS grades(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER,subject_id INTEGER,value INTEGER,date TEXT,FOREIGN KEY(student_id) REFERENCES students(id),FOREIGN KEY(subject_id) REFERENCES subjects(id));CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,title TEXT,body TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,subscription TEXT NOT NULL);`);
const q={userByEmail:db.prepare('SELECT * FROM users WHERE email=?'),userById:db.prepare('SELECT * FROM users WHERE id=?'),student:db.prepare('SELECT * FROM students WHERE id=?'),grades:db.prepare('SELECT g.*,s.name subject FROM grades g JOIN subjects s ON s.id=g.subject_id WHERE g.student_id=? ORDER BY g.date DESC'),subjects:db.prepare('SELECT * FROM subjects')};
if(!q.userByEmail.get('teacher@demo.local')){const hash=bcrypt.hashSync('1234',10);const t=db.prepare('INSERT INTO users(email,password,name,role) VALUES(?,?,?,?)').run('teacher@demo.local',hash,'Учитель Demo','teacher');const s=db.prepare('INSERT INTO students(name,class_name) VALUES(?,?)').run('Ученик Demo','10-А');db.prepare('INSERT INTO users(email,password,name,role,student_id) VALUES(?,?,?,?,?)').run('student@demo.local',hash,'Ученик Demo','student',s.lastInsertRowid);db.prepare('INSERT INTO users(email,password,name,role,student_id) VALUES(?,?,?,?,?)').run('parent@demo.local',hash,'Родитель Demo','parent',s.lastInsertRowid);for(const n of ['Математика','Английский'])db.prepare('INSERT INTO subjects(name) VALUES(?)').run(n);const math=db.prepare('SELECT id FROM subjects WHERE name=?').get('Математика').id;const eng=db.prepare('SELECT id FROM subjects WHERE name=?').get('Английский').id;db.prepare('INSERT INTO grades(student_id,subject_id,value,date) VALUES(?,?,?,?)').run(s.lastInsertRowid,math,9,'2026-08-17');db.prepare('INSERT INTO grades(student_id,subject_id,value,date) VALUES(?,?,?,?)').run(s.lastInsertRowid,eng,8,'2026-08-16');}
const secret=process.env.JWT_SECRET||'dev-only-secret-change-me';
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),secret);next()}catch{res.status(401).json({error:'Unauthorized'})}}
function token(u){return jwt.sign({id:u.id,role:u.role,studentId:u.student_id||null},secret,{expiresIn:'7d'})}
app.get('/api/health',(req,res)=>res.json({ok:true,time:new Date().toISOString()}));
app.post('/api/auth/login',async(req,res)=>{const u=q.userByEmail.get(String(req.body.email||'').trim());if(!u||!(await bcrypt.compare(String(req.body.password||''),u.password)))return res.status(401).json({error:'Неверный email или пароль'});res.json({token:token(u),user:{id:u.id,email:u.email,name:u.name,role:u.role,studentId:u.student_id}})});
app.get('/api/me',auth,(req,res)=>{const u=q.userById.get(req.user.id);res.json({id:u.id,email:u.email,name:u.name,role:u.role,studentId:u.student_id})});
app.get('/api/students',auth,(req,res)=>{if(req.user.role!=='teacher')return res.status(403).json({error:'Forbidden'});res.json(db.prepare('SELECT * FROM students ORDER BY name').all())});
app.get('/api/students/:id/grades',auth,(req,res)=>{const id=Number(req.params.id);if(req.user.role!=='teacher'&&req.user.studentId!==id)return res.status(403).json({error:'Forbidden'});res.json(q.grades.all(id))});
app.post('/api/grades',auth,(req,res)=>{if(req.user.role!=='teacher')return res.status(403).json({error:'Forbidden'});const {studentId,subjectId,value,date}=req.body;if(!Number.isInteger(Number(value))||Number(value)<1||Number(value)>10)return res.status(400).json({error:'Оценка должна быть от 1 до 10'});const r=db.prepare('INSERT INTO grades(student_id,subject_id,value,date) VALUES(?,?,?,?)').run(studentId,subjectId,value,date||new Date().toISOString().slice(0,10));res.status(201).json({id:r.lastInsertRowid})});
app.get('/api/analytics/:studentId',auth,(req,res)=>{const id=Number(req.params.studentId);if(req.user.role!=='teacher'&&req.user.studentId!==id)return res.status(403).json({error:'Forbidden'});const grades=q.grades.all(id);const avg=grades.length?grades.reduce((a,g)=>a+g.value,0)/grades.length:0;const bySubject={};for(const g of grades)(bySubject[g.subject]??=[]).push(g.value);const subjects=Object.fromEntries(Object.entries(bySubject).map(([k,v])=>[k,{average:v.reduce((a,x)=>a+x,0)/v.length,count:v.length}]));res.json({average:Number(avg.toFixed(2)),count:grades.length,weak:grades.filter(g=>g.value<=5).length,subjects})});
app.post('/api/ai/analyze',auth,async(req,res)=>{const id=Number(req.body.studentId||req.user.studentId);if(req.user.role!=='teacher'&&req.user.studentId!==id)return res.status(403).json({error:'Forbidden'});const grades=q.grades.all(id);const prompt=`Проанализируй успеваемость ученика. Данные JSON: ${JSON.stringify(grades)}. Дай краткий нейтральный анализ: сильные стороны, предметы для внимания и 3 конкретных учебных шага.`;if(!process.env.AI_BASE_URL||!process.env.AI_API_KEY)return res.json({configured:false,text:'AI-провайдер не настроен. Локальная аналитика доступна через /api/analytics/:studentId.',prompt});try{const r=await fetch(`${process.env.AI_BASE_URL.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.AI_API_KEY}`},body:JSON.stringify({model:process.env.AI_MODEL||'gpt-4o-mini',messages:[{role:'system',content:'Ты помощник школьного журнала. Не ставь диагнозы, не сравнивай детей по личности и не раскрывай приватные данные.'},{role:'user',content:prompt}],temperature:.2})});const j=await r.json();res.json({configured:true,text:j.choices?.[0]?.message?.content||'AI не вернул ответ'})}catch(e){res.status(502).json({error:'AI provider unavailable'})}});
app.post('/api/notifications/subscribe',auth,(req,res)=>{db.prepare('INSERT INTO subscriptions(user_id,subscription) VALUES(?,?)').run(req.user.id,JSON.stringify(req.body));res.status(201).json({ok:true})});
app.post('/api/notifications/send',auth,async(req,res)=>{if(req.user.role!=='teacher')return res.status(403).json({error:'Forbidden'});const {userId,title='School Journal',body='Новое уведомление'}=req.body;db.prepare('INSERT INTO notifications(user_id,title,body,created_at) VALUES(?,?,?,?)').run(userId,title,body,new Date().toISOString());if(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY){webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:admin@example.com',process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);const rows=db.prepare('SELECT subscription FROM subscriptions WHERE user_id=?').all(userId);for(const x of rows)try{await webpush.sendNotification(JSON.parse(x.subscription),JSON.stringify({title,body}))}catch{}}res.status(201).json({ok:true})});
app.get('/api/notifications',auth,(req,res)=>res.json(db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC').all(req.user.id)));
app.get('/api/report/:studentId.pdf',auth,(req,res)=>{const id=Number(req.params.studentId);if(req.user.role!=='teacher'&&req.user.studentId!==id)return res.status(403).end();const s=q.student.get(id);const grades=q.grades.all(id);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`inline; filename="report-${id}.pdf"`);const doc=new PDFDocument();doc.pipe(res);doc.fontSize(20).text('School Journal Report');doc.moveDown();doc.fontSize(13).text(`Student: ${s?.name||id}`);doc.text(`Class: ${s?.class_name||''}`);const avg=grades.length?grades.reduce((a,g)=>a+g.value,0)/grades.length:0;doc.text(`Average: ${avg.toFixed(2)}`);doc.moveDown();grades.forEach(g=>doc.text(`${g.date||''} — ${g.subject}: ${g.value}`));doc.end()});
app.listen(Number(process.env.PORT)||3000,()=>console.log(`School Journal API: http://localhost:${process.env.PORT||3000}`));
